
# scripts: These javascript files will be packaged and linked
# in order before any other .js files. File paths should be 
# specified relative to the project root. They should not be 
# compressed. 

scripts:
- libraries/scripts/backlift-reloader.js
- libraries/scripts/jquery.js
- libraries/scripts/jquery.cookie.js
- libraries/scripts/underscore.js
- libraries/scripts/backbone.js
- libraries/scripts/bootstrap.js
- libraries/scripts/date.js
- libraries/scripts/backlift-backbone-helpers.js
- libraries/scripts/backlift-commonview.js
- app/**/*.js


# styles: These stylesheets will be packaged and linked
# in order before any other .css files, similar to scripts.

styles:
- libraries/styles/bootstrap.css
- app/**/*.css


# autoroute: the automatic routing feature is useful for single-page 
# websites that implement their own javascript routing. If autoroute
# is set to 'yes', all requests to URLs that don't match a file or API 
# endpoint will be routed to the index.html file. Default is 'no'.

autoroute: yes


collections:
  profiles:
    _public_permissions: { default: 'r', readonly: yes }
    following: { type: 'list', default: [] }
  tweaks:
    message: { type: 'string', max: 25, required: yes }

# packages: define sets of additional libraries or functionality that
# can be downloaded during app installation. Top-level key defines 
# package name. Inside package, each key is a folder name, and each 
# value is a github repository or gist. Github repos may specify a tag 
# or branch via a tree url.

packages:
  include:
    admin: 
    - github.com/backlift/backlift-admin
    libraries: 
    - github.com/backlift/backbone-bundle/tree/20130406
    - github.com/backlift/bootstrap-bundle/tree/20130406
    libraries/scripts: 
    - gist.github.com/backliftapp/5606343 # backlift-reloader.js
    - gist.github.com/backlift/5334085 # backlift-commonview.js  

# require: which of the packages must be installed during 

require:
- include