# -------------------------------------------------------------------
# Backlift config.yml file. This file can be used to customize how 
# your application is packaged when you run backlift push.
# -------------------------------------------------------------------

# compile: Backlift will select an appropriate compiler for each file 
# that matches one of the patterns below. The file types that backlift 
# recognizes are:
#   *.jst        -> underscore templates (outputs .js files)
#   *.handlebars -> handlebars templates (outputs .js files)
#   *.less       -> lessc css compiler (outputs .css files)
#   *.coffee     -> coffeescript compiler (outputs .js files)
#
# Uncomment this block to customize which files will be compiled:

# compile:
# - public/**/*.jst
# - public/**/*.handlebars
# - public/**/bootstrap*.less
# - public/**/*.coffee


# scripts: These javascript files will be packaged and linked in 
# order. File paths should be specified relative to the project root.
# They should not be compressed. The * will match any string and **
# will match any folder.

scripts:
- public/libraries/scripts/jquery.js
- public/libraries/scripts/underscore.js
- public/libraries/scripts/backbone.js
- public/libraries/scripts/bootstrap.js
- public/**/*.js


# styles: These stylesheets will be packaged and linked in order, 
# similar to scripts.

styles:
- public/libraries/styles/bootstrap.css
- public/**/*.css


# optimize: The optimize flag controls whether or not backlift 
# concatenates and minifies .js and .css files. The optimizer is slow
# and produces obfuscated code that cannot be easily debugged. For 
# these reasons, optimization should be disabled during development

optimize: no


# autoroute: the automatic routing feature is useful for single-page 
# websites that implement their own javascript routing. If autoroute
# is set to 'yes', all requests to URLs that don't match a file or API 
# endpoint will be routed to the index.html file. Default is 'no'.

autoroute: yes


# packages: define sets of additional libraries or functionality that
# can be downloaded during app installation. Top-level key defines 
# package name. Inside package, each key is a folder name, and each 
# value is a github repository or gist. Github repos may specify a tag 
# or branch via a tree url.

packages:
  include:
    admin: 
    - github.com/backlift/backlift-admin
    libraries: 
    - github.com/backlift/backbone-bundle/tree/20130406
    - github.com/backlift/bootstrap-bundle/tree/20130406

# require: which of the packages must be installed during 

require:
- include