# -------------------------------------------------------------------
# Backlift config.yml file. This file can be used to customize how 
# your application is packaged when you run backlift push.
# -------------------------------------------------------------------

# includes: Files and folders to be included when app is installed.
# These files reside only in the backlift server and thus don't clutter
# your folder on Dropbox.

include:
  admin: github.com/backlift/backlift-admin